### ISSUE TITLE
Error: spawn pdfinfo ENOENT

### ISSUE THREAD

**Issue by OhDavit** [zetahernandez/pdf-to-text#8]
I have the following code:

`
   var pdfUtil = require('pdf-to-text');
`
 `  var pdf_path = "./some.pdf";
`
  ` pdfUtil.info(pdf_path, function(err, info) {
 `    
  `if (err) throw('error = ' + err);
`
  `    console.log(info.split(' ').length);
}`);

which causes the following exception.

      throw er; // Unhandled 'error' event
      ^

Error: spawn pdfinfo ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Davits-MBP:xx davitohanyan$ vim index.js
Davits-MBP:xx davitohanyan$ vim index.js
Davits-MBP:xx davitohanyan$ vim index.js
Davits-MBP:xx davitohanyan$ node index.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn pdfinfo ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Quetzacoalt91** [comment]
We had the same issue here. Check the package `poppler-utils` is installed on your machine.

**Comment by aziznatour** [comment]
@Quetzacoalt91 this package does not exist, tests fail too.

**Comment by Aarbel** [comment]
@Quetzacoalt91 your answer fixed it for us
